name: appt_app
description: Demo Appointment App
version: 0.4.8

environment:
  sdk: ">=2.1.0 <3.0.0"
 
dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2 
  intl: ^0.16.0
  provider: ^3.1.0
  firebase_auth: ^0.14.0
  google_sign_in: ^4.0.7
  flutter_facebook_login: ^2.0.1
  google_maps_flutter: ^0.5.21
  carousel_slider: ^1.3.1
  shimmer: 1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/best-barber.jpg
    - assets/images/barber-1.jpg
    - assets/images/barber-2.jpg
    - assets/images/barber-3.jpg 
    - assets/images/icons/apple-pay-48.png
    - assets/images/icons/visa-48.png
    - assets/images/icons/mastercard-48.png
    - assets/images/icons/american-express-48.png
    - assets/images/icons/twitter-48.png
    - assets/images/icons/facebook-logo.png
    - assets/images/icons/google-logo.png
  fonts:
    - family: PlayfairDisplay
      fonts:
        - asset: assets/fonts/PlayfairDisplay-Regular.ttf
        - asset: assets/fonts/PlayfairDisplay-Italic.ttf
          style: italic
        - asset: assets/fonts/PlayfairDisplay-Bold.ttf
          weight: 700

